language: python
python:
  - "2.6"
  - "2.7"
env:
  - TEST_TYPE=unit
  - TEST_TYPE=functional

install:
  - pip install -r requirements.txt

script:
  - make $TEST_TYPE


branches:
  only:
    - master
